export default function Head() {
  return (
    <>
      <title>Google Shopping Alejandro</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <meta
        name="google-site-verification"
        content="zZ-35Ozcz8RzTFsm0Dhoawt1O8RE04UPv1kVzDYhzJo"
      />
    </>
  );
}
